name: ad_platform-dev
services:
  db:
    image: surrealdb/surrealdb:v2.2
    restart: on-failure
    user: root
    volumes:
      - db-data:/var/lib/surrealdb
    command:
      - start
    ports:
      - 8001:8000
    environment:
      SURREAL_USER: root
      SURREAL_PASS: root
      SURREAL_PATH: rocksdb:/var/lib/surrealdb
  grafana:
    restart: always
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana:rw
    environment:
      GF_PLUGINS_PREINSTALL: yesoreyeram-infinity-datasource
  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-18T16-25-55Z
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: beetroot
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
    command: minio server /data
volumes:
  db-data:
  grafana-data:
  minio-data:
